sudo: false
dist: bionic
addons:
  hosts:
    # To prevent to access real example.org
    - example.org

language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    # Because current PHP recommended version is 7.4+.
    # @see https://wordpress.org/support/article/requirements/
    # PHP 7.4 is already end of life.
    # @see https://www.php.net/supported-versions.php
    - php: 8.0
      env: WP_VERSION=latest PHPUNIT_REQUIRE="*" MOCKERY_REQUIRE="*"
    # Because now PHP 8.0 is in the Active Support period and should be focused in development.
    # @see https://www.php.net/supported-versions.php
    # According to commit message of this definition,
    # the trunk version seems to should be tested by current major support PHP version.
    # @see:
    # - Rebuild `.travis.yml` file · wp-cli/scaffold-command@fe11bcc
    #   https://github.com/wp-cli/scaffold-command/commit/fe11bcc02a2ee164c987e2cb14fcb08dfe73663b
    - php: 8.0
      env: WP_VERSION=trunk PHPUNIT_REQUIRE="*" MOCKERY_REQUIRE="*"
    - php: 8.0
      env: WP_TRAVISCI=phpcs
    # Because 3.7 is the version which start support for auto background update. However, test can't work.
    # 3.7 - 3.8: When init database before running PHPUnit, wp-includes/wp-db.php db_connect() calls mysql_connect().
    # 3.9 - 4.2: wp-includes/class-phpass.php PasswordHash has a deprecated constructor.
    # @see https://make.wordpress.org/core/handbook/about/release-cycle/releasing-minor-versions/#security
    # Because WordPress 4.3 doesn't support PHP 7.2.
    # When call activate_plugin(),
    # count(): Parameter must be an array or an object that implements Countable
    # /wp-includes/kses.php:900
    - php: 7.1
      env: WP_VERSION=4.3 PHPUNIT_REQUIRE="4.8.*|5.7.*"
      # Because WordPress 4.3 doesn't support MySQL 5.7.
      # WordPress database error Unknown system variable 'storage_engine' for query SET storage_engine = INNODB
      # in wordpress-test-lib/includes/install.php
      # @see https://docs.travis-ci.com/user/database-setup/#mysql
      dist: trusty
    - php: 7.4
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
      # Because Ubuntu 18.04 on Travis doesn't support PHP 7.0.
      dist: xenial
    # Because of minimum support version.
    # @see https://wordpress.org/news/2019/04/minimum-php-version-update/
    # @see https://ubuntu.com/about/release-cycle
    - php: 5.6
      env: WP_VERSION=latest
      dist: trusty
  allow_failures:
    # Because there are too match errors and warnings,
    # however now it needs to leave codes to prioritize merging commits from other forked repositories.
    - php: 8.0
      env: WP_TRAVISCI=phpcs

before_script:
  # Travis CI introduced phpenv, composer global bin dir no longer refered without phpenv-composer plugin.
  # @see https://ngyuki.hatenablog.com/entry/2014/03/09/054239
  - git clone https://github.com/ngyuki/phpenv-composer.git ~/.phpenv/plugins/phpenv-composer
  - phpenv rehash
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      # It seems to have to be not localhost but 127.0.0.1 on Ubuntu 18.04 .
      # @see https://stackoverflow.com/a/41997588
      bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
      PHPUNIT_REQUIRE="${PHPUNIT_REQUIRE:-4.8.*|5.7.*|<8.0.0}"
      MOCKERY_REQUIRE="${MOCKERY_REQUIRE:-1.3.*}"
      composer global require "phpunit/phpunit:$PHPUNIT_REQUIRE" yoast/phpunit-polyfills "mockery/mockery:$MOCKERY_REQUIRE"
      phpenv rehash
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer phpcompatibility/phpcompatibility-wp automattic/vipwpcs
      phpenv rehash
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi
