sudo: false
dist: bionic
addons:
  hosts:
    # To prevent to access real example.org
    - example.org

language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    # Because current PHP recommended version is 7.3+.
    # @see https://wordpress.org/support/article/requirements/
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    # Because now PHP 7.2 is in the Active Support period and should be focused in development.
    # @see https://www.php.net/supported-versions.php
    - php: 7.2
      env: WP_VERSION=trunk
    # Because 3.7 is the version which start support for auto background update. However, test can't work.
    # 3.7 - 3.8: When init database before running PHPUnit, wp-includes/wp-db.php db_connect() calls mysql_connect().
    # 3.9 - 4.2: wp-includes/class-phpass.php PasswordHash has a deprecated constructor.
    # @see https://make.wordpress.org/core/handbook/about/release-cycle/releasing-minor-versions/#security
    - php: 7.2
      env: WP_VERSION=4.3
    - php: 7.2
      env: WP_TRAVISCI=phpcs
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
      # because Ubuntu 18.04 on Travis doesn't support PHP 7.0.
      dist: xenial
    # Because of minimum support version.
    # @see https://wordpress.org/news/2019/04/minimum-php-version-update/
    # @see https://ubuntu.com/about/release-cycle
    - php: 5.6
      env: WP_VERSION=latest
      dist: trusty
  allow_failures:
    # Because there are too match errors and warnings,
    # however now it needs to leave codes to prioritize merging commits from other forked repositories.
    - php: 7.2
      env: WP_TRAVISCI=phpcs

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      # It seems to have to be not localhost but 127.0.0.1 on Ubuntu 18.04 .
      # @see https://stackoverflow.com/a/41997588
      bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer phpcompatibility/phpcompatibility-wp automattic/vipwpcs mockery/mockery
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi
