name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - wordpress-image-tag: latest
           modernity: modern
         - wordpress-image-tag: 4.3-apache
           modernity: legacy
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/plugins/staticpress2019
      - id: set_branch_name
        run: |
          if [ "${IS_PULL_REQUEST}" = true ]
          then
              echo "::set-output name=branch_name::$(echo ${GITHUB_HEAD_REF#refs/heads/} | sed 's/\//_/g')"
          else
              echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
          fi
        env:
          IS_PULL_REQUEST: ${{ startsWith( github.ref, 'refs/pull/' ) }}
      - uses: actions/checkout@v2
        with:
          repository: yukihiko-shinoda/docker-compose-jest-puppeteer-staticpress2019
          ref: ${{ steps.set_branch_name.outputs.branch_name }}
          path: ${{ github.workspace }}/docker-compose-jest-puppeteer-staticpress2019
      - run: docker-compose -f docker-compose.test.yml run --rm puppeteer
        working-directory: ${{ github.workspace }}/docker-compose-jest-puppeteer-staticpress2019
        env:
          PATH_TO_PLUGIN_DIRECTORY: ${{ github.workspace }}/plugins
          WORDPRESS_IMAGE_TAG: ${{ matrix.wordpress-image-tag }}
          MODERNITY: ${{ matrix.modernity }}
